# Copyright (c) 2020-2021 the Mondradiko contributors.
# SPDX-License-Identifier: LGPL-3.0-or-later

name = "Transform"

[methods]

  [methods.getPosition]
  brief = "Retrieves the position of this Transform."
  return = ["double", "double", "double"]

  [methods.setPosition]
  brief = "Sets the position of this Transform."
  params = ["double", "double", "double"]
