# Copyright (c) 2020 the Mondradiko contributors.
# SPDX-License-Identifier: LGPL-3.0-or-later

name = "Transform"

[methods]

  [methods.getPosition]
  brief = "Retrieves the position of this Transform."
  params = ["int32_t"]
  params_wasm = ["i32"]
  return = "Vec3"
  return_wasm = ["f64", "f64", "f64"]

  [methods.setPosition]
  brief = "Sets the position of this Transform."
  params = ["int32_t", "double", "double", "double"]
  params_wasm = ["i32", "f64", "f64", "f64"]
