title: Mondradiko
description: Mondradiko is a future-proof VR engine for creating multiplayer virtual reality experiences.
theme: jekyll-theme-midnight

plugins:
  - jekyll-readme-index

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false
