# Copyright (c) 2020 Marceline Cramer
# SPDX-License-Identifier: LGPL-3.0-or-later

name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Compile
        shell: bash
        run: |
          mkdir builddir
          pushd builddir
          cmake -GNinja ..
          ninja
          popd
