name: continuous-integration

on: [push, pull_request]

jobs:
  src-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: cpplint --recursive ./src/
