name: Code Style Check

on: [push, pull_request]

jobs:
  cpplint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: cpplint --recursive ./src/
