name: Code Style Check

on:
  push:
    paths:
      - "src/**.cc"
      - "src/**.h"
  pull_request:
    paths:
      - "src/**.cc"
      - "src/**.h"

jobs:
  cpplint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: cpplint --recursive ./src/
