# Copyright (c) 2020 Marceline Cramer
# SPDX-License-Identifier: LGPL-3.0-or-later

name: Code Style Check

on:
  push:
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"

jobs:
  cpplint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - name: Style Check
        shell: bash
        run: |
          pushd src
          ./style_check.sh
          popd
